// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:rentrover/utils/constants.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Secrets.webApiKey,
    appId: Secrets.webAppId,
    messagingSenderId: Secrets.messagingSenderId,
    projectId: Secrets.projectId,
    authDomain: Secrets.authDomain,
    storageBucket: Secrets.storageBucket,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Secrets.androidApiKey,
    appId: Secrets.androidAppId,
    messagingSenderId: Secrets.messagingSenderId,
    projectId: Secrets.projectId,
    storageBucket: Secrets.storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Secrets.iosApiKey,
    appId: Secrets.iosAppId,
    messagingSenderId: Secrets.messagingSenderId,
    projectId: Secrets.projectId,
    storageBucket: Secrets.storageBucket,
    iosBundleId: Secrets.iosBundleId,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: Secrets.iosApiKey,
    appId: Secrets.iosAppId,
    messagingSenderId: Secrets.messagingSenderId,
    projectId: Secrets.projectId,
    storageBucket: Secrets.storageBucket,
    iosBundleId: Secrets.iosBundleId,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: Secrets.webApiKey,
    appId: Secrets.windowsAppId,
    messagingSenderId: Secrets.messagingSenderId,
    projectId: Secrets.projectId,
    authDomain: Secrets.authDomain,
    storageBucket: Secrets.storageBucket,
  );
}
