// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLCXj02HXseKJgG4dH8aDG9KwtgbCZStw',
    appId: '1:517822928552:web:ecafadc5054dfae923949d',
    messagingSenderId: '517822928552',
    projectId: 'rentrover-07',
    authDomain: 'rentrover-07.firebaseapp.com',
    storageBucket: 'rentrover-07.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDey2oDAWsXJwwX23Nki8OC1oPJH5RWZI',
    appId: '1:517822928552:android:425b9a4356f4965523949d',
    messagingSenderId: '517822928552',
    projectId: 'rentrover-07',
    storageBucket: 'rentrover-07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm5GXKe8dGy-1oTodip2hCdazTA8pENLQ',
    appId: '1:517822928552:ios:4d495dc2e324932b23949d',
    messagingSenderId: '517822928552',
    projectId: 'rentrover-07',
    storageBucket: 'rentrover-07.firebasestorage.app',
    iosBundleId: 'com.example.rentrover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm5GXKe8dGy-1oTodip2hCdazTA8pENLQ',
    appId: '1:517822928552:ios:4d495dc2e324932b23949d',
    messagingSenderId: '517822928552',
    projectId: 'rentrover-07',
    storageBucket: 'rentrover-07.firebasestorage.app',
    iosBundleId: 'com.example.rentrover',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLCXj02HXseKJgG4dH8aDG9KwtgbCZStw',
    appId: '1:517822928552:web:aa4e801b70582d4023949d',
    messagingSenderId: '517822928552',
    projectId: 'rentrover-07',
    authDomain: 'rentrover-07.firebaseapp.com',
    storageBucket: 'rentrover-07.firebasestorage.app',
  );
}
